const nextStages = {
    
    PENDING_LEAD: ["COMPLETE_REGISTRATION", "SANCTION_PENDING"], 
    COMPLETE_REGISTRATION: ["BRE_APPROVED"],
    BRE_APPROVED: ["SANCTION_PENDING", "SANCTION_COMPLETED"],
    SANCTION_PENDING: ["SANCTION_COMPLETED", "DISBURSED"], 
    SANCTION_COMPLETED: ["DISBURSED"],
    DISBURSED: ["DISBURSAL_FAILED", "APPLY_RELOAN"], 
    APPLY_RELOAN: ["PENDING_LEAD"], 
    BRE_REJECT: ["MANNULY_REJECT"],
    MANNULY_REJECT: [],
    MANNULY_APPROVE: ["DISBURSED"],
    SEND_AADHAAR_OTP: ["VERIFY_AADHAAR_KYC", "ADD_ADDRESS"], 
    VERIFY_AADHAAR_KYC: ["VALIDATE_PERSONAL_EMAIL"],
    VALIDATE_PERSONAL_EMAIL: ["ADD_ADDRESS"],
    ADD_ADDRESS: ["SANCTION_PENDING"],
    REJECT_AADHAR_KYC: ["MANNULY_REJECT"],
    SEND_OFFICE_EMAIL_OTP: ["VRIFY_OFFICE_EMAIL"],
    VRIFY_OFFICE_EMAIL: ["ADD_ADDRESS"],
        
};
  
function getNextStages(currentStage) {
    return nextStages[currentStage] || [];
  }